#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get -y install nginx

echo "Ceci n'est pas une page" > etc/nginx/html/404.html

echo '{
	listen 80;
	listen [::]:80;

	server_name _;

	location /redirect me{
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	
	error_page 404 /404.html;
	location = /404.hmtl{
		root /etc/nginx/html;
		internal;	
}


}
' > /etc/nginx/sites-available/default

service nginx start
