#!/bin/env bash

apt-get update
apt-get install -y nginx

echo 'server {
  listen 80 default_server;
  listen [::]:80 default_server;
  

  root www/var/html;
  index index.html index.htm index.nginx-debian.html;

  server_name _;

  location / {
     try_files $uri $uri/ =404;
    add_header X-Served-By $HOSTNAME;
  }
}' > /etc/nginx/sites-available/default

service nginx restart
