#!/usr/bin/env bash
# Bash script to config a new Ubuntu machine nginx

sudo apt-get update
sudo apt-get install -y nginx

# Add custom HTTP response header to Nginx configuration
echo 'server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	
	server_name _;
	
	location / {
		try_files $uri $uri/ =404;
		add_header X-Served-By $HOSTNAME;
	}
}' > /etc/nginx/sites-available/default

# Add custom HTTP response header to Nginx configuration
sudo service nginx restart
