#!/usr/bin/env bash
# Bash script to install and configure HAproxy on my lb-01 server

apt-get update
apt-get install -y haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend
backend lb-backend
    mode http
    balance roundrobin
    server web-01 514727-web-01 54.197.130.4:80 check
    server web-02 514727-web-02 52.91.160.210:80 check
EOF

service haproxy restart
