#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1

while [ $i -le 20 ]; do
	case $i in
		5) echo "bad luck from China"
			;;
		9) echo "bad luck from Japan"
			;;
		17) echo "bad luck from Italy"
			;;
		*) echo "$i"
	esac
	((i++))
done
