#!/usr/bin/env bash
# Script that replaces nginx user
sudo sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
pkill apache2

sudo service nginx restart
